services:
  - type: web
    name: ai-classifieds
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
